services:
  db:
    container_name: postgres
    image: postgres:18
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    build: .
    container_name: coderr_backend
    env_file: 
      - .env.prod
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - coderr_media:/app/media
      - coderr_static:/app/static
    restart: unless-stopped


volumes:
  postgres_data:
  coderr_media:
  coderr_static: