# Generated by Django 6.0.7 on 2026-07-16 22:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=' ', max_length=75)),
                ('last_name', models.CharField(default=' ', max_length=75)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('location', models.CharField(default='', max_length=150)),
                ('tel', models.CharField(default=' ')),
                ('description', models.TextField(default=' ', max_length=300)),
                ('working_hours', models.CharField(default=' ', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
